---
- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf.j2
    dest: "{{ mariadb_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  notify: restart mysql

- name: Set ownership on slow query log file (if configured).
  file:
    path: "{{ mariadb_slow_query_log_file }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0644
  when: mariadb_slow_query_log_enabled

- name: Start MySQL daemon
  systemd:
    name: "{{ mariadb_deamon }}"
    state: started
    daemon_reload: yes
    enabled: yes
