---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Add mariadb repo
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root
    group: root

- name: Install mariadb packages
  yum:
    name:
      - MariaDB-server
      - MariaDB-client
      - MySQL-python
      - mysqltuner
      - MariaDB-devel
    state: present
    update_cache: yes
  notify:
    - delete ib_logfiles

- name: Starting mariadb
  service:
    name: mysql
    state: started
    enabled: yes
