---
- name: Install depended packages
  apt:
    name: gnupg
    state: present

- name: Add MariaDB apt key
  apt_key:
    id: "0xF1656F24C74CD1D8"
    keyserver: "hkp://keyserver.ubuntu.com:80"

- name: Add MariaDB repository
  apt_repository:
    repo: "deb [arch=amd64] https://ftp.harukasan.org/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: mariadb

- name: Install mariadb packages
  apt:
    name:
      - mariadb-server
      - python-mysqldb
      - mysqltuner
    state: present
    update_cache: yes
  notify:
    - delete ib_logfiles

- name: Starting mariadb
  service:
    name: mysql
    state: started
    enabled: yes
