---
- name: Install depended packaages
  apt:
    name:
      - gnupg
    state: present

- name: Add MariaDB apt key
  apt_key:
    id: "0xF1656F24C74CD1D8"
    keyserver: "hkp://keyserver.ubuntu.com:80"

- name: Add MariaDB repository
  apt_repository:
    repo: "{{ mariadb_debian_repo }}"
    state: present
    filename: mariadb

- name: Install mariadb packages
  apt:
    name:
      - mariadb-server
      - python-mysqldb
      - mysqltuner
    state: present
    update_cache: yes
  notify:
    - delete ib_logfiles

- name: Starting mariadb
  systemd:
    name: mariadb
    state: started
    enabled: yes
