---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define mysql_daemon.
  set_fact:
    mariadb_deamon: "{{ __mariadb_daemon }}"
  when: mariadb_daemon is not defined

- name: Install OS packages
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Configuring MySQL-server
  import_tasks: configure.yml

- name: Security installation
  import_tasks: secure_installation.yml
