---
- name: Get list of hosts for the root user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mysql_root_hosts
  changed_when: false

- name: Update MySQL root password for localhost root account.
  mysql_user: name="root" host={{ item }} password={{ mariadb_root_password }}
  with_items: "{{ mysql_root_hosts.stdout_lines }}"

- name: Copy .my.cnf file with root password credentials.
  template:
    src: "user-my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Remove MySQL test database.
  mysql_db: "name='test' state=absent"
