---
- name: restart mysql
  systemd:
    name: mysql
    state: restarted
    enabled: yes

- name: delete ib_logfiles
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/mysql/ib_logfile0
    - /var/lib/mysql/ib_logfile1
